import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-parcel-ltl-invoice-audit-recovery",
  "engine": "recovery",
  "title": "Parcel & LTL Invoice Audit Recovery",
  "shortTitle": "Freight Invoice Recovery",
  "tagline": "Audit every shipment charge, recover credits, and prevent recurring logistics leakage",
  "industry": "Transportation Spend Recovery",
  "uiPort": 4553,
  "apiPort": 5553,
  "accent": "#b45309",
  "currency": "USD",
  "primaryOutcome": "Freight overcharges and service failures converted into verified credits",
  "valueNarrative": "Reconstruct shipment rating from contracts, manifests, scans, invoices, dimensions, service commitments, and proof of delivery.",
  "calculation": {
    "actualKey": "billedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Carrier billed amount",
    "expectedLabel": "Contract-supported amount",
    "varianceLabel": "Potential freight recovery",
    "direction": "actual-minus-expected",
    "finding": "Shipment-rating and service evidence indicate recoverable freight leakage.",
    "actions": [
      "Re-rate the shipment using the effective carrier agreement",
      "Validate dimensions, weight, accessorials, and scan events",
      "Submit the refund or service-guarantee claim",
      "Reconcile carrier credit and prevent recurrence"
    ]
  }
},[
feature("carrier-contract-and-rate-card-library","FIR01","Carrier contract and rate-card library","Reconcile carrier contract and rate-card library using carrier agreements, rate cards, manifests, scan events, dimensions, accessorial rules, invoices, and proof of delivery.","Produce a governed carrier contract and rate-card library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrier","Carrier","text","Northstar Parcel"],["trackingNumber","Tracking / PRO Number","text","1Z88420260718"],["billedAmount","Carrier Billed Amount","currency",18450],["supportedAmount","Contract-Supported Amount","currency",14220]],{amountField:"billedAmount",subjects:["Parcel shipment","LTL shipment","International parcel","Residential delivery","Guaranteed service shipment"]}),
feature("shipment-manifest-ingestion","FIR02","Shipment manifest ingestion","Reconcile shipment manifest ingestion using carrier agreements, rate cards, manifests, scan events, dimensions, accessorial rules, invoices, and proof of delivery.","Produce a governed shipment manifest ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrier","Carrier","text","Northstar Parcel"],["trackingNumber","Tracking / PRO Number","text","1Z88420260718"],["billedAmount","Carrier Billed Amount","currency",18450],["supportedAmount","Contract-Supported Amount","currency",14220]],{amountField:"billedAmount",subjects:["Parcel shipment","LTL shipment","International parcel","Residential delivery","Guaranteed service shipment"]}),
feature("invoice-and-edi-ingestion","FIR03","Invoice and EDI ingestion","Reconcile invoice and edi ingestion using carrier agreements, rate cards, manifests, scan events, dimensions, accessorial rules, invoices, and proof of delivery.","Produce a governed invoice and edi ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrier","Carrier","text","Northstar Parcel"],["trackingNumber","Tracking / PRO Number","text","1Z88420260718"],["billedAmount","Carrier Billed Amount","currency",18450],["supportedAmount","Contract-Supported Amount","currency",14220]],{amountField:"billedAmount",subjects:["Parcel shipment","LTL shipment","International parcel","Residential delivery","Guaranteed service shipment"]}),
feature("base-rate-recalculation","FIR04","Base-rate recalculation","Reconcile base-rate recalculation using carrier agreements, rate cards, manifests, scan events, dimensions, accessorial rules, invoices, and proof of delivery.","Produce a governed base-rate recalculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrier","Carrier","text","Northstar Parcel"],["trackingNumber","Tracking / PRO Number","text","1Z88420260718"],["billedAmount","Carrier Billed Amount","currency",18450],["supportedAmount","Contract-Supported Amount","currency",14220]],{amountField:"billedAmount",subjects:["Parcel shipment","LTL shipment","International parcel","Residential delivery","Guaranteed service shipment"]}),
feature("dim-weight-validation","FIR05","DIM-weight validation","Reconcile dim-weight validation using carrier agreements, rate cards, manifests, scan events, dimensions, accessorial rules, invoices, and proof of delivery.","Produce a governed dim-weight validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrier","Carrier","text","Northstar Parcel"],["trackingNumber","Tracking / PRO Number","text","1Z88420260718"],["billedAmount","Carrier Billed Amount","currency",18450],["supportedAmount","Contract-Supported Amount","currency",14220]],{amountField:"billedAmount",subjects:["Parcel shipment","LTL shipment","International parcel","Residential delivery","Guaranteed service shipment"]}),
feature("accessorial-charge-validation","FIR06","Accessorial charge validation","Reconcile accessorial charge validation using carrier agreements, rate cards, manifests, scan events, dimensions, accessorial rules, invoices, and proof of delivery.","Produce a governed accessorial charge validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrier","Carrier","text","Northstar Parcel"],["trackingNumber","Tracking / PRO Number","text","1Z88420260718"],["billedAmount","Carrier Billed Amount","currency",18450],["supportedAmount","Contract-Supported Amount","currency",14220]],{amountField:"billedAmount",subjects:["Parcel shipment","LTL shipment","International parcel","Residential delivery","Guaranteed service shipment"]}),
feature("fuel-surcharge-audit","FIR07","Fuel-surcharge audit","Reconcile fuel-surcharge audit using carrier agreements, rate cards, manifests, scan events, dimensions, accessorial rules, invoices, and proof of delivery.","Produce a governed fuel-surcharge audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrier","Carrier","text","Northstar Parcel"],["trackingNumber","Tracking / PRO Number","text","1Z88420260718"],["billedAmount","Carrier Billed Amount","currency",18450],["supportedAmount","Contract-Supported Amount","currency",14220]],{amountField:"billedAmount",subjects:["Parcel shipment","LTL shipment","International parcel","Residential delivery","Guaranteed service shipment"]}),
feature("duplicate-invoice-detection","FIR08","Duplicate invoice detection","Reconcile duplicate invoice detection using carrier agreements, rate cards, manifests, scan events, dimensions, accessorial rules, invoices, and proof of delivery.","Produce a governed duplicate invoice detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrier","Carrier","text","Northstar Parcel"],["trackingNumber","Tracking / PRO Number","text","1Z88420260718"],["billedAmount","Carrier Billed Amount","currency",18450],["supportedAmount","Contract-Supported Amount","currency",14220]],{amountField:"billedAmount",subjects:["Parcel shipment","LTL shipment","International parcel","Residential delivery","Guaranteed service shipment"]}),
feature("late-delivery-guarantee-recovery","FIR09","Late-delivery guarantee recovery","Reconcile late-delivery guarantee recovery using carrier agreements, rate cards, manifests, scan events, dimensions, accessorial rules, invoices, and proof of delivery.","Produce a governed late-delivery guarantee recovery decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrier","Carrier","text","Northstar Parcel"],["trackingNumber","Tracking / PRO Number","text","1Z88420260718"],["billedAmount","Carrier Billed Amount","currency",18450],["supportedAmount","Contract-Supported Amount","currency",14220]],{amountField:"billedAmount",subjects:["Parcel shipment","LTL shipment","International parcel","Residential delivery","Guaranteed service shipment"]}),
feature("address-correction-validation","FIR10","Address-correction validation","Reconcile address-correction validation using carrier agreements, rate cards, manifests, scan events, dimensions, accessorial rules, invoices, and proof of delivery.","Produce a governed address-correction validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrier","Carrier","text","Northstar Parcel"],["trackingNumber","Tracking / PRO Number","text","1Z88420260718"],["billedAmount","Carrier Billed Amount","currency",18450],["supportedAmount","Contract-Supported Amount","currency",14220]],{amountField:"billedAmount",subjects:["Parcel shipment","LTL shipment","International parcel","Residential delivery","Guaranteed service shipment"]}),
feature("ltl-class-and-density-audit","FIR11","LTL class and density audit","Reconcile ltl class and density audit using carrier agreements, rate cards, manifests, scan events, dimensions, accessorial rules, invoices, and proof of delivery.","Produce a governed ltl class and density audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrier","Carrier","text","Northstar Parcel"],["trackingNumber","Tracking / PRO Number","text","1Z88420260718"],["billedAmount","Carrier Billed Amount","currency",18450],["supportedAmount","Contract-Supported Amount","currency",14220]],{amountField:"billedAmount",subjects:["Parcel shipment","LTL shipment","International parcel","Residential delivery","Guaranteed service shipment"]}),
feature("minimum-charge-and-discount-audit","FIR12","Minimum-charge and discount audit","Reconcile minimum-charge and discount audit using carrier agreements, rate cards, manifests, scan events, dimensions, accessorial rules, invoices, and proof of delivery.","Produce a governed minimum-charge and discount audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrier","Carrier","text","Northstar Parcel"],["trackingNumber","Tracking / PRO Number","text","1Z88420260718"],["billedAmount","Carrier Billed Amount","currency",18450],["supportedAmount","Contract-Supported Amount","currency",14220]],{amountField:"billedAmount",subjects:["Parcel shipment","LTL shipment","International parcel","Residential delivery","Guaranteed service shipment"]}),
feature("carrier-dispute-packet-generation","FIR13","Carrier dispute packet generation","Reconcile carrier dispute packet generation using carrier agreements, rate cards, manifests, scan events, dimensions, accessorial rules, invoices, and proof of delivery.","Produce a governed carrier dispute packet generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrier","Carrier","text","Northstar Parcel"],["trackingNumber","Tracking / PRO Number","text","1Z88420260718"],["billedAmount","Carrier Billed Amount","currency",18450],["supportedAmount","Contract-Supported Amount","currency",14220]],{amountField:"billedAmount",subjects:["Parcel shipment","LTL shipment","International parcel","Residential delivery","Guaranteed service shipment"]}),
feature("credit-and-refund-reconciliation","FIR14","Credit and refund reconciliation","Reconcile credit and refund reconciliation using carrier agreements, rate cards, manifests, scan events, dimensions, accessorial rules, invoices, and proof of delivery.","Produce a governed credit and refund reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrier","Carrier","text","Northstar Parcel"],["trackingNumber","Tracking / PRO Number","text","1Z88420260718"],["billedAmount","Carrier Billed Amount","currency",18450],["supportedAmount","Contract-Supported Amount","currency",14220]],{amountField:"billedAmount",subjects:["Parcel shipment","LTL shipment","International parcel","Residential delivery","Guaranteed service shipment"]}),
feature("carrier-lane-and-leakage-analytics","FIR15","Carrier lane and leakage analytics","Reconcile carrier lane and leakage analytics using carrier agreements, rate cards, manifests, scan events, dimensions, accessorial rules, invoices, and proof of delivery.","Produce a governed carrier lane and leakage analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrier","Carrier","text","Northstar Parcel"],["trackingNumber","Tracking / PRO Number","text","1Z88420260718"],["billedAmount","Carrier Billed Amount","currency",18450],["supportedAmount","Contract-Supported Amount","currency",14220]],{amountField:"billedAmount",subjects:["Parcel shipment","LTL shipment","International parcel","Residential delivery","Guaranteed service shipment"]})
]);
